version: "3.8"

services:
  app:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: api
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - laravel
    depends_on:
      - db

  composer:
    image: composer:2
    container_name: composer
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: metricalo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
